source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'

gem 'sass', '~> 3.4.0'

gem 'rocket_cms_activerecord', '~> 0.8.12'

gem 'sass-rails'
gem 'compass-rails', '~> 2.0.0'
gem 'compass', '~> 1.0.0'

gem 'slim-rails'
gem 'rs_russian'
gem 'cancancan'

gem 'cloner'
gem 'unicorn'
gem 'x-real-ip'

gem 'sentry-raven'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
  gem 'spring'

  gem 'capistrano', '~> 3.4.0', require: false
  gem 'rvm1-capistrano3', require: false
  gem 'glebtv-capistrano-unicorn', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-rails', require: false

  gem 'hipchat'
  #gem 'coffee-rails-source-maps'
  #gem 'compass-rails-source-maps'
end

group :test do
  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'email_spec'
  
  gem 'ffaker'
  gem 'factory_girl_rails'
end

